name: Go Build and Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' 

    - name: Build & Test
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install libx11-dev -y
        mkdir -p /tmp/runner
        go build -o /tmp/runner/cogent . && /tmp/runner/cogent -testcheck true && rm -rf /tmp/runner
