name: Release Cogent

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write # If you plan to release to other package registries

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}